///<reference path="World.ts"/>
///<reference path="Interpreter.ts"/>
///<reference path="Graph.ts"/>

/**
* Planner module
*
* The goal of the Planner module is to take the interpetation(s)
* produced by the Interpreter module and to plan a sequence of actions
* for the robot to put the world into a state compatible with the
* user's command, i.e. to achieve what the user wanted.
*
* The planner should use your A* search implementation to find a plan.
*/
module Planner {

    //////////////////////////////////////////////////////////////////////
    // exported functions, classes and interfaces/types

    /**
     * Top-level driver for the Planner. Calls `planInterpretation` for each given interpretation generated by the Interpreter.
     * @param interpretations List of possible interpretations.
     * @param currentState The current state of the world.
     * @returns Augments Interpreter.InterpretationResult with a plan represented by a list of strings.
     */
    export function plan(interpretations : Interpreter.InterpretationResult[], currentState : WorldState) : PlannerResult[] {
        var errors : Error[] = [];
        var plans : PlannerResult[] = [];
        interpretations.forEach((interpretation) => {
            try {
                var result : PlannerResult = <PlannerResult>interpretation;
                result.plan = planInterpretation(result.interpretation, currentState);
                if (result.plan.length == 0) {
                    result.plan.push("That is already true!");
                }
                plans.push(result);
            } catch(err) {
                errors.push(err);
            }
        });
        if (plans.length) {
            return plans;
        } else {
            // only throw the first error found
            throw errors[0];
        }
    }

    export interface PlannerResult extends Interpreter.InterpretationResult {
        plan : string[];
    }

    export function stringify(result : PlannerResult) : string {
        return result.plan.join(", ");
    }

    function StringifyState(state : WorldState): string {
      var s :string = "";
      for(var i : number = 0; i < state.stacks.length; i++) {
        for(var j : number = 0; j < state.stacks.length; j++) {
          if(state.stacks[i][j] == undefined){
            continue;
          }
          s+=state.stacks[i][j];
        }
        s+="+";
      }
      s+=state.arm;
      s+=state.holding;
      return s;
    }
    class StateGraph implements Graph<WorldState>{
      /** Computes the edges that leave from a node. */
      outgoingEdges(node : WorldState) : Edge<WorldState>[] {
        return null; //TODO
      }
      /** A function that compares nodes. */
      compareNodes(s1 : WorldState, s2 : WorldState) : number {
        return null; //TODO
      }
    }
    //returns all possible actions in the current world state, "r" "l" "p" "d"
    function getPossibleActions(w1 : WorldState) : string[] {
      return null;
    }

    //////////////////////////////////////////////////////////////////////
    // private functions

    /**
     * The core planner function. The code here is just a template;
     * you should rewrite this function entirely. In this template,
     * the code produces a dummy plan which is not connected to the
     * argument `interpretation`, but your version of the function
     * should be such that the resulting plan depends on
     * `interpretation`.
     *
     *
     * @param interpretation The logical interpretation of the user's desired goal. The plan needs to be such that by executing it, the world is put into a state that satisfies this goal.
     * @param state The current world state.
     * @returns Basically, a plan is a
     * stack of strings, which are either system utterances that
     * explain what the robot is doing (e.g. "Moving left") or actual
     * actions for the robot to perform, encoded as "l", "r", "p", or
     * "d". The code shows how to build a plan. Each step of the plan can
     * be added using the `push` method.
     */
    function planInterpretation(interpretation : Interpreter.DNFFormula, state : WorldState) : string[] {
      var stateGraph : StateGraph = new StateGraph();

      //TODO heuristics function
      var heuristics = function huer(node : WorldState) : number {
        return 0;
      }
      var goalFunction = function goalf(node : WorldState) : boolean {
        var world : WorldState = node; // how do we make this happen?
        var result : boolean = false;
        for(var i : number = 0; i < interpretation.length; i++) {
            var l : Interpreter.Literal = interpretation[i][0]; //assuming just 1 literal per potential goal
            var subResult : boolean = Interpreter.matchesRelation(l.args[0] ,l.args[1], l.relation, world);
            if(!l.polarity) {
                subResult = !subResult;
            }
            result = result || subResult;
        }
        return result;
      }

      aStarSearch(stateGraph,state,goalFunction,heuristics,10);

      //TODO use aStarSearchs result to rebuiled the path


        // This function returns a dummy plan involving a random stack
        do {
            var pickstack = Math.floor(Math.random() * state.stacks.length);
        } while (state.stacks[pickstack].length == 0);
        var plan : string[] = [];

        // First move the arm to the leftmost nonempty stack
        if (pickstack < state.arm) {
            plan.push("Moving left");
            for (var i = state.arm; i > pickstack; i--) {
                plan.push("l");
            }
        } else if (pickstack > state.arm) {
            plan.push("Moving right");
            for (var i = state.arm; i < pickstack; i++) {
                plan.push("r");
            }
        }

        // Then pick up the object
        var obj = state.stacks[pickstack][state.stacks[pickstack].length-1];
        plan.push("Picking up the " + state.objects[obj].form,
                  "p");

        if (pickstack < state.stacks.length-1) {
            // Then move to the rightmost stack
            plan.push("Moving as far right as possible");
            for (var i = pickstack; i < state.stacks.length-1; i++) {
                plan.push("r");
            }

            // Then move back
            plan.push("Moving back");
            for (var i = state.stacks.length-1; i > pickstack; i--) {
                plan.push("l");
            }
        }

        // Finally put it down again
        plan.push("Dropping the " + state.objects[obj].form,
                  "d");

        return plan;
    }
}
